apiVersion: v1
kind: Service
metadata:
  name: postgres-pago
  labels:
    app: postgres-pago
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-pago
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-pago
  labels:
    app:  postgres-pago
spec:
  selector:
    matchLabels:
      app: postgres-pago
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-pago
    spec:
      containers:
        - image: postgres:latest
          name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-user-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-user-credentials
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-db
                  key: name1
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-pago-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-pago-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pago-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pago-pv-claim
  labels:
    app: postgres-pago
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi